### ISSUE TITLE
Arduino library

### ISSUE THREAD

**Issue by d-a-v** [laukik-hase/OTA_update_AVR_using_ESP32#1]
Coming [from another arduino library](https://github.com/rene-win/esp_avr_programmer/issues/5#issuecomment-667708396),
I wonder if this repository could also be compatible with arduino (ie: used as an arduino library) ?

**Comment by laukik-hase** [comment]
This repository was built with the ESP-IDF platform for ESP32. All the functions incorporated are based on the STK500 communication protocol for AVR MCUs. Also, you can find the logic for parsing the hex files here. So, you can port them to the Arduino platform, but that will take some work.

**Comment by laukik-hase** [comment]
@d-a-v I am closing this issue for now. You can reopen it for any further doubts.
