### ISSUE TITLE
There was no 'Example Configuration' in idf.py menuconfig

### ISSUE THREAD

**Issue by Albert245** [laukik-hase/OTA_update_AVR_using_ESP32#4]
Hi, I'm now following your project. Found out there was no 'Example Configuration' in the menuconfig. Is there anything changed ? I'm new to this ESP-IDF so please help. 
![image_2022-11-21_005027429](https://user-images.githubusercontent.com/89130689/202917788-b6526b0d-e4d3-4feb-8fd4-30f8b1783430.png)

**Comment by zama737** [comment]
Hi, did struggle with this one as well. After succesful build using ESP-IDF command line tools, idf.py build, it did show up. 

Did change ssid and password using menuconfig, flashed and it worked.

**Comment by udit7395** [comment]
[Solution](https://github.com/ESP32-Musings/OTA_update_AVR_using_ESP32/issues/4#issuecomment-1343373568)
